---
- name: install 3 containers of web_app
  hosts: webserver
  become: yes
  vars:
    docker_login: 'elenazhelezova'
    docker_image: 'elenazhelezova/exam_devops:web_app'
    port_dict:
      '1': '172.1.1.20'
      '2': '172.1.1.21'
      '3': '172.1.1.22'

  tasks:
    - name: Install epel-release, python
      yum:
        name:
          - epel-release
          - python
          - python-pip

    - name: Install docker-py
      pip:
        name: docker-py

    - name: Create docker network
      docker_network:
        name: web_net
        ipam_config:
          - subnet: 172.1.1.0/24

    - name: Include web_app role
      include_role:
         name: web_app

    - name: Include nginx role
      include_role:
        name: nginx_balancer


