- name: Install yum-utils
  yum:
    name: yum-utils
    state: present

- name: Add docker repo
  yum_repository:
    name: docker
    description: Docker repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable

- name: yum update
  yum:
    name: '*'
    state: latest

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg

- name: Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Start docker
  ansible.builtin.service:
    name: docker
    state: started