---
# tasks file for web_app

- name: Install docker for CentOs
  import_tasks: install_docker_centos.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: Pull web_app docker image
  import_tasks: pull_from_private_repo.yml
