- name: login dockerhub
  docker_login:
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"

- name: Run docker container
  docker_container:
    name: "web_app_{{ item.key }}"
    image: "{{ docker_image }}"
    state: started
    networks:
      - name: web_net
        ipv4_address: "{{ item.value }}"
  with_dict: "{{ port_dict }}"

- name: Logout dockerhub
  docker_login:
    state: absent